#!/usr/bin/env bash
# test/regression/make_htscodecs_guard.sh
#
# Regression: the root Makefile refuses to build htslib on top of an
# overwritten ext/htslib/htscodecs_bundled.mk, and says how to restore it.
#
# Was: htslib's configure installs htscodecs.mk as a symlink to the bundled
# fragment, and htslib's own fallback recipe for htscodecs.mk regenerates it by
# writing through that symlink — GNU make remakes included makefiles even
# under -n, and `make -B` marks them out of date. The fragment became a
# comment-only stub, libhts.a was archived without the rans/tok3 objects, and
# the build died at the final link with undefined `rans_*` symbols, well away
# from the cause.
#
# The check drives the Makefile's standalone entry point for the guard
# (`make check-htscodecs-fragment`, the same statement the $(HTS_LIB) recipe
# runs before and after its htslib sub-make): it must pass on the healthy
# tree, fail with the restore hint once the fragment is overwritten the way
# htslib's recipe overwrites it, and pass again after the fragment is put
# back. The fragment is restored on every exit path.
#
# Inputs:
#   MAKE      — make binary (default: make)
#   MAKE_ARGS — extra make arguments (e.g. "CXX=clang++-19"); the Makefile's
#               parse-time compiler check runs even for this target.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

MAKE="${MAKE:-make}"
MAKE_ARGS="${MAKE_ARGS:-}"
FRAG=ext/htslib/htscodecs_bundled.mk
LINK=ext/htslib/htscodecs.mk

run_make() {
    # MAKE_ARGS is intentionally word-split: it carries zero or more arguments.
    # shellcheck disable=SC2086
    "$MAKE" $MAKE_ARGS "$@"
}

if [[ ! -L "$LINK" ]]; then
    echo "FAIL: $LINK is not a symlink — htslib is not configured; run this against a built tree"
    exit 1
fi
if ! grep -q '^HTSCODECS_OBJS' "$FRAG"; then
    echo "FAIL: $FRAG is already overwritten — restore it (git -C ext/htslib checkout -- htscodecs_bundled.mk) before running this check"
    exit 1
fi

BACKUP="$(mktemp)"
OUT="$(mktemp)"
cp -p "$FRAG" "$BACKUP"
trap 'cp -p "$BACKUP" "$FRAG"; rm -f "$BACKUP" "$OUT"' EXIT

# --- 1. Healthy tree: the guard must stay quiet.
if ! run_make check-htscodecs-fragment > "$OUT" 2>&1; then
    echo "FAIL: guard fired on a healthy tree:"
    cat "$OUT"
    exit 1
fi

# --- 2. Overwritten fragment: the stub htslib's htscodecs.mk recipe writes
# --- through the symlink (comment lines only, no HTSCODECS_OBJS).
printf '# Generated by htslib configure/Makefile fallback -- stub\n' > "$FRAG"
if run_make check-htscodecs-fragment > "$OUT" 2>&1; then
    echo "FAIL: guard did not fire on the overwritten fragment"
    exit 1
fi
if ! grep -q 'has been overwritten' "$OUT"; then
    echo "FAIL: guard failed without its explanation:"
    cat "$OUT"
    exit 1
fi
if ! grep -q 'git -C ext/htslib checkout -- htscodecs_bundled.mk' "$OUT"; then
    echo "FAIL: guard fired without the restore command:"
    cat "$OUT"
    exit 1
fi

# --- 3. Restored: quiet again, so the check leaves the tree as it found it.
cp -p "$BACKUP" "$FRAG"
if ! run_make check-htscodecs-fragment > "$OUT" 2>&1; then
    echo "FAIL: guard still fires after the fragment was restored:"
    cat "$OUT"
    exit 1
fi

echo "PASS: htscodecs fragment guard is quiet on a healthy tree, fails with the restore hint on an overwritten one, and is quiet again after restore"
