#!/usr/bin/env bash
# test/regression/make_header_deps.sh
#
# Regression: every object the root Makefile builds is recompiled when a header
# it includes changes.
#
# Was: header dependencies came from a checked-in `makedepend` block regenerated
# by hand, which listed nothing for any test/*.o and nothing for four src TUs.
# Those objects were never rebuilt when a header changed, so an incremental build
# linked an object compiled against the *old* struct layout into a library built
# against the new one — a silent ODR violation, not benign staleness.
#
# It last showed up when `worker_t` grew `smem_sort_scratch[MAX_THREADS]` ahead
# of `nthreads` (#278), moving that field's offset. A stale kt_for_pool_test.o
# kept writing `w->nthreads` at the old offset, kt_for() read zero at the new one
# and clamped the pool to one worker, and the test failed claiming the worker pool
# was not persistent — pointing at threading rather than at the build.
#
# Two checks, because they fail in different ways:
#
#   coverage — every object in the Makefile's own object lists has a .d naming at
#     least one header. Enumerated via `make print-<VAR>` rather than a copy of
#     the lists, so a compile rule added without $(DEPFLAGS) fails here even
#     though no probe names its object. This is what catches the next hole.
#   wiring — touching a header really does recompile a dependent object. Proves
#     the -include side works, which the .d files existing does not.
#
# Deliberately not `make -q`: it answers "is anything in the graph out of date",
# and this tree always has something. `htslib_static.mk` is -include'd and
# generated by a rule on `libhts.a`, which the htslib build leaves a second
# newer, so `make -q` reports work pending for every target — `make -q bwa-mem3`
# does too, with nothing to do.
#
# Inputs:
#   MAKE      — make binary (default: make)
#   MAKE_ARGS — extra make arguments, e.g. "arch=avx2 USE_MIMALLOC=1". Pass the
#               flags the tree was built with: the wiring check recompiles, and
#               an object rebuilt at different flags than the library it is
#               archived into is the hazard this test exists to catch.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

MAKE="${MAKE:-make}"
MAKE_ARGS="${MAKE_ARGS:-}"

# Object-list variables that must carry generated dependencies. KERNEL_TIER_OBJS
# is empty on arm64 (single NEON tier) and LIBSAIS_OBJS lives in a submodule;
# both are covered here rather than special-cased.
OBJ_VARS=(OBJS KERNEL_TIER_OBJS NATIVE_KERNEL_OBJS STANDALONE_TEST_OBJS LIBSAIS_OBJS)

# The wiring probe: an object plus a header it includes only indirectly
# (src/seed_order.cpp reaches bwamem.h via seed_order.h), since indirect
# includes are what a hand-maintained list loses first.
PROBE_OBJ=src/seed_order.o
PROBE_HEADER=src/bwamem.h

fail=0

run_make() {
    # MAKE_ARGS is intentionally word-split: it carries zero or more arguments.
    # shellcheck disable=SC2086
    "$MAKE" $MAKE_ARGS "$@"
}

# Whole-second mtime. Deliberately not `[ a -nt b ]`: bash compares with
# nanosecond precision, but GNU Make 3.81 — Apple's stock make, and what this
# repo builds with on macOS — compares whole seconds. A header 0.3 s newer than
# its object looks newer to bash and unchanged to make, which made an earlier
# version of this test report a missing dependency that was recorded correctly.
#
# Probed once rather than chained as `stat -f %m || stat -c %Y`: the two spellings
# are not fallbacks for each other. GNU's -f is --file-system, not a format flag,
# so on Linux `stat -f %m FILE` prints a multi-line "File: ..." report for FILE
# (and fails only on the literal `%m`), the || never reaches the GNU form cleanly,
# and that text lands in the arithmetic below as a bareword -- "File: unbound
# variable" under `set -u`.
if stat -c %Y . > /dev/null 2>&1; then
    mtime_sec() { stat -c %Y "$1"; } # GNU coreutils
else
    mtime_sec() { stat -f %m "$1"; } # BSD / macOS
fi

# ---------------------------------------------------------------------------
# Check 1: coverage — every built object has a .d listing headers.
# ---------------------------------------------------------------------------
objects=()
for var in "${OBJ_VARS[@]}"; do
    # `read -a` rather than mapfile: bash 3.2 (macOS) has no mapfile, and the
    # variable expands to one space-separated line of object paths.
    read -r -a var_objs <<< "$(run_make -s "print-$var")"
    objects+=("${var_objs[@]}")
done

if ((${#objects[@]} == 0)); then
    echo "FAIL: no objects enumerated from ${OBJ_VARS[*]} — is print-% missing?"
    exit 1
fi

checked=0 skipped=0
for obj in "${objects[@]}"; do
    # Only objects that have actually been built can have a .d yet, so an unbuilt
    # object is skipped rather than failed — but a run where *everything* was
    # skipped verified nothing, and is failed below.
    [[ -f "$obj" ]] || {
        skipped=$((skipped + 1))
        continue
    }
    checked=$((checked + 1))
    dep="${obj%.o}.d"
    if [[ ! -s "$dep" ]]; then
        echo "FAIL: $obj has no dependency file ($dep) — its compile rule is missing" \
            "\$(DEPFLAGS), or the object predates it and has not been recompiled"
        fail=1
    elif ! grep -q "^$obj:" "$dep"; then
        # A .d that does not declare its own object is not wired to anything.
        # Deliberately not asserting it names a header: src/kopen.cpp includes
        # only system headers, which -MMD skips by design, so its .d correctly
        # lists just the .cpp.
        echo "FAIL: $dep does not declare $obj as a target"
        fail=1
    fi
done
echo "coverage: $checked objects checked, $skipped not built"
if ((checked == 0)); then
    echo "FAIL: no built objects to check — run this against a built tree"
    fail=1
fi

# ---------------------------------------------------------------------------
# Check 2: wiring — a header change really does recompile a dependent object.
# ---------------------------------------------------------------------------
MTIME_REF="$(mktemp)"
TOUCHED_HEADER=""

restore_header() {
    # Put the mtime back so the next build does not see a spurious change.
    # Content is never modified, only the timestamp.
    [[ -n "$TOUCHED_HEADER" ]] && touch -r "$MTIME_REF" "$TOUCHED_HEADER" 2> /dev/null || true
    TOUCHED_HEADER=""
}
trap 'restore_header; rm -f "$MTIME_REF"' EXIT

if [[ ! -f "$PROBE_HEADER" ]]; then
    echo "FAIL: $PROBE_HEADER does not exist — the probe is stale"
    fail=1
elif ! run_make "$PROBE_OBJ" > /dev/null; then
    echo "FAIL: could not build $PROBE_OBJ — a build failure, not a dependency finding"
    fail=1
else
    touch -r "$PROBE_HEADER" "$MTIME_REF"
    TOUCHED_HEADER="$PROBE_HEADER"

    # The header has to land a whole second past the object: make treats equal
    # second-granularity mtimes as up to date, and the build above routinely
    # finishes in the same second as the touch — indistinguishable from a missing
    # dependency. (`touch -d` / `-A` spellings differ GNU vs BSD, hence sleep.)
    obj_mtime="$(mtime_sec "$PROBE_OBJ")"
    for _ in 1 2 3; do
        touch "$PROBE_HEADER"
        (($(mtime_sec "$PROBE_HEADER") > obj_mtime)) && break
        sleep 1
    done

    if (($(mtime_sec "$PROBE_HEADER") <= obj_mtime)); then
        echo "FAIL: could not make $PROBE_HEADER newer than $PROBE_OBJ (timestamp granularity?)"
        fail=1
    elif ! run_make "$PROBE_OBJ" > /dev/null; then
        echo "FAIL: rebuild of $PROBE_OBJ failed after touching $PROBE_HEADER"
        fail=1
    elif [[ "$(mtime_sec "$PROBE_OBJ")" == "$obj_mtime" ]]; then
        echo "FAIL: $PROBE_OBJ was NOT recompiled after touching $PROBE_HEADER"
        echo "      (dependency recorded but not included — check the -include line)"
        fail=1
    else
        echo "wiring: $PROBE_OBJ recompiled after $PROBE_HEADER changed"
    fi
    restore_header
fi

if ((fail != 0)); then
    echo "FAIL: root Makefile header dependencies are incomplete"
    exit 1
fi
echo "PASS: header dependencies generated and wired for all built objects"
