#!/usr/bin/env bash
# scripts/rescue_knobs.sh — print the BWA3_RESCUE_* knob table as Markdown.
#
# Single source of truth: the list between the `rescue-knobs:begin` and
# `rescue-knobs:end` markers in src/rescue_env.h, one knob per line (name,
# default, meaning; continuation lines are indented past the name column). The
# "Read in" column is derived: every file under src/ holding the knob's name as a
# string literal. `make docs-rescue-knobs` writes the output to
# docs/_generated/rescue/knobs.md, which docs/src/developer-guide/rescue.md
# includes; test/regression/rescue_docs_lint.sh fails when the committed file
# differs from this script's output.
#
# Usage: rescue_knobs.sh [repo-root]   (the argument lets the lint's self-test aim
# the generator at a fixture tree)

set -euo pipefail

if (($# > 1)); then
    echo "usage: ${BASH_SOURCE[0]##*/} [repo-root]" >&2
    exit 2
fi
root="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
env_h="$root/src/rescue_env.h"
if [[ ! -f $env_h ]]; then
    echo "error: $env_h is not a regular file" >&2
    exit 1
fi

# name <TAB> default <TAB> meaning, one line per knob, in list order.
knobs="$(awk '
    /^ \* rescue-knobs:begin/ { on = 1; next }
    /^ \* rescue-knobs:end/ { on = 0; done = 1; next }
    !on { next }
    {
        line = $0
        sub(/^ \*[ ]?/, "", line)
        if (line ~ /^BWA3_RESCUE_[A-Z0-9_]+[ ]/) {
            if (n) print name "\t" dflt "\t" meaning
            n++
            split(line, f, /[ ]+/)
            name = f[1]; dflt = f[2]
            meaning = line
            sub(/^[^ ]+[ ]+[^ ]+[ ]+/, "", meaning)
        } else {
            sub(/^[ ]+/, "", line)
            if (line != "") meaning = meaning " " line
        }
    }
    END {
        if (n) print name "\t" dflt "\t" meaning
        if (!done) exit 3
    }
' "$env_h")" || {
    echo "error: $env_h has no complete rescue-knobs:begin / rescue-knobs:end list" >&2
    exit 1
}
if [[ -z $knobs ]]; then
    echo "error: the rescue-knobs list in $env_h is empty" >&2
    exit 1
fi

echo "<!-- Generated by scripts/rescue_knobs.sh from the rescue-knobs list in src/rescue_env.h."
echo "     Do not edit: run \`make docs-rescue-knobs\` and commit the result. -->"
echo
echo "| Variable | Default | Read in | Meaning |"
echo "|---|---|---|---|"
while IFS=$'\t' read -r name dflt meaning; do
    files=""
    while IFS= read -r f; do
        [[ -n $f ]] && files+="${files:+, }\`src/${f##*/}\`"
    done < <(grep -lF "\"$name\"" "$root"/src/*.c "$root"/src/*.cpp "$root"/src/*.h 2> /dev/null | sort || true)
    echo "| \`$name\` | \`$dflt\` | ${files:-none} | ${meaning//|/\\|} |"
done <<< "$knobs"
